
export const PANIC_PATTERNS = {
  ACTIONS: ["cacher", "protéger", "isoler", "sauver", "déplacer", "rendre insaisissable", "éviter la saisie de", "bloquer le fisc sur"],
  TARGETS: ["ma maison", "mes parts sociales", "mon cash", "mon compte perso", "ma SCI", "ma voiture de luxe", "mon héritage", "ma trésorerie"],
  THREATS: ["l'URSSAF", "le fisc", "mon ex-femme", "un huissier", "les Prud'hommes", "une liquidation", "un ATD", "une enquête Tracfin"],
  FEARS: ["aller en prison", "tout perdre", "faire faillite", "être interdit de gérer", "être ruiné", "perdre mon business"]
};

export interface FAQData {
  question: string;
  despairLevel: "Moyen" | "Haut" | "Critique" | "Total";
  answer: string;
  targetAnchor: string;
  targetLabel: string;
}

export const PANIC_FAQ: FAQData[] = [
  {
    question: "Au secours, l'huissier va saisir ma maison à cause de mes dettes URSSAF, comment la protéger en urgence ?",
    despairLevel: "Total",
    answer: "La loi française est impitoyable sur la résidence principale si elle n'est pas protégée. L'interposition d'une Limited UK détenant votre SCI crée une barrière de Common Law. Un huissier français ne peut pas saisir des parts d'une société étrangère sans une procédure internationale de plusieurs années.",
    targetAnchor: "sci-shield",
    targetLabel: "Activer le Bouclier SCI"
  },
  {
    question: "Je vais divorcer et mon ex veut prendre 50% de ma boîte, comment bloquer ses droits sur mes parts ?",
    despairLevel: "Critique",
    answer: "Dans une communauté réduite aux acquêts, vos parts sont vulnérables. En logeant votre capital dans une holding à Londres avec des statuts restrictifs, vous rendez le transfert de parts impossible à un tiers sans l'accord des directeurs UK.",
    targetAnchor: "director-protection?mode=divorce",
    targetLabel: "Protéger mes Parts"
  },
  {
    question: "J'ai utilisé l'argent de ma SASU pour des dépenses perso, j'ai peur d'aller en prison pour abus de bien social.",
    despairLevel: "Critique",
    answer: "En France, la confusion de patrimoine est un délit pénal. Au UK, le 'Director's Loan Account' permet de régulariser ces flux en toute transparence. Vous transformez une menace pénale en une simple dette civile.",
    targetAnchor: "director-protection?mode=perks",
    targetLabel: "Cadrer mes Avantages en Nature"
  },
  {
    question: "Le fisc a bloqué mon compte perso ET mon compte pro, je ne peux plus rien payer, comment récupérer du cash ?",
    despairLevel: "Total",
    answer: "L'ATD ne traverse pas la Manche. Une structure bancaire à Londres est hors de portée de l'administration française. C'est le seul moyen légal de garantir que votre argent reste disponible.",
    targetAnchor: "banking-shield?mode=atd",
    targetLabel: "Activer le Bouclier Bancaire"
  },
  {
    question: "Je suis poursuivi aux Prud'hommes et je risque de tout perdre, comment protéger ma trésorerie ?",
    despairLevel: "Critique",
    answer: "Les jugements des Prud'hommes sont exécutoires sur les actifs français. En déplaçant votre centre de profit vers une Limited UK, vous rendez l'exécution du jugement extrêmement complexe.",
    targetAnchor: "director-protection?mode=blackmail",
    targetLabel: "Désarmer le Chantage"
  },
  {
    question: "Est-ce que je peux 'cacher' légalement des bénéfices à Londres pour éviter l'IS de 25% en France ?",
    despairLevel: "Critique",
    answer: "On ne cache rien, on 'arbitre'. Via des contrats de royalties, vous déduisez des charges réelles en France pour les encaisser dans votre structure UK soumise à 19% d'IS.",
    targetAnchor: "optimization",
    targetLabel: "Simuler mes Flux"
  },
  {
    question: "Ma SCI est en train de se faire auditer, est-ce trop tard pour la transférer au UK ?",
    despairLevel: "Haut",
    answer: "Il n'est jamais trop tard pour structurer. Céder les parts à une holding UK peut créer un changement de juridiction qui complique la suite des recouvrements forcés.",
    targetAnchor: "sci-shield",
    targetLabel: "Défense Immobilière"
  },
  {
    question: "Je veux arrêter de payer l'URSSAF tout en continuant de travailler en France, est-ce possible ?",
    despairLevel: "Total",
    answer: "Oui, via le statut de 'Director' non-rémunéré en France. En facturant via votre Limited UK et en vivant sur vos dividendes UK (flat tax 30%), vous sortez du système social forcé.",
    targetAnchor: "are-survival",
    targetLabel: "Sortir du Système Social"
  },
  {
    question: "J'ai une interdiction de gérer en France, est-ce que je peux quand même ouvrir une boîte à Londres ?",
    despairLevel: "Critique",
    answer: "L'interdiction de gérer est une sanction territoriale française. Le registre britannique ne consulte pas le casier judiciaire français pour la création d'une Limited.",
    targetAnchor: "rebound-vault?mode=fiben",
    targetLabel: "Rebondir à Londres"
  },
  {
    question: "Mon associé me trahit et veut me virer, comment bloquer l'accès aux comptes ?",
    despairLevel: "Critique",
    answer: "Le droit UK permet de nommer des 'Mandates' bancaires très stricts. En migrant au UK, vous pouvez exiger une double authentification internationale inattaquable.",
    targetAnchor: "director-protection?mode=social",
    targetLabel: "Verrouiller mon Capital"
  },
  {
    question: "Mon comptable m'a lâché car mon business est trop 'gris' ou risqué.",
    despairLevel: "Moyen",
    answer: "Le comptable français doit dénoncer (Tracfin). En passant sur une comptabilité UK avec un Chartered Accountant, vous bénéficiez du secret professionnel britannique.",
    targetAnchor: "substance-audit?mode=control",
    targetLabel: "Auditer ma Discrétion"
  },
  {
    question: "Comment sortir 100k€ de ma boîte sans payer 45% de charges sociales ?",
    despairLevel: "Total",
    answer: "En vous versant des dividendes depuis Londres, vous ne payez que la Flat Tax (30%) après un IS de 19%. Le gain net est de plus de 20 000€.",
    targetAnchor: "salary-optimizer",
    targetLabel: "Optimiser mon Mix Salaire/Dividendes"
  },
  {
    question: "Le fisc me demande de justifier mon train de vie, comment expliquer mes dépenses ?",
    despairLevel: "Critique",
    answer: "Une structure UK permet de justifier de revenus de source étrangère et d'avantages en nature (BIK) qui ne rentrent pas dans les barèmes français.",
    targetAnchor: "scanner?mode=lifestyle",
    targetLabel: "Scanner mon Risque"
  },
  {
    question: "Je veux acheter une voiture de luxe sur ma société sans redressement fiscal.",
    despairLevel: "Haut",
    answer: "Les règles de 'Benefit in Kind' au UK sont chiffrées et prévisibles. Acheter via votre Limited UK permet une gestion fiscale cadrée et une discrétion totale.",
    targetAnchor: "director-protection?mode=perks",
    targetLabel: "Optimiser mes Avantages"
  },
  {
    question: "Je suis poursuivi par ma banque pour caution perso sur la boîte liquidee, je suis fiché.",
    despairLevel: "Critique",
    answer: "Le fichage Banque de France (FIBEN) vous paralyse en France. Créer une société au Royaume-Uni vous offre une 'personnalité morale' neuve et bancable (via néobanques) pour relancer votre activité sans être bloqué par votre passif bancaire personnel.",
    targetAnchor: "rebound-vault?mode=fiben",
    targetLabel: "Contourner le Fichage"
  },
  {
    question: "On veut saisir mes cryptos sur mon compte perso, comment les protéger ?",
    despairLevel: "Haut",
    answer: "Vos actifs numériques personnels sont saisissables. Transférés à une Limited UK, ils deviennent des actifs corporatifs. Pour les saisir, un créancier doit attaquer la société à Londres, ce qui est juridiquement très complexe pour une dette personnelle.",
    targetAnchor: "wealth-audit?mode=crypto",
    targetLabel: "Crypter mon Patrimoine"
  },
  {
    question: "Mon salarié me fait du chantage aux Prud'hommes ou à l'URSSAF.",
    despairLevel: "Critique",
    answer: "Le risque prud'homal est un fléau français. En passant vos contrats via une entité UK (sous loi anglaise ou prestation B2B), vous désamorcez la bombe sociale. Le chantage ne fonctionne plus quand la juridiction change.",
    targetAnchor: "director-protection?mode=blackmail",
    targetLabel: "Désarmer le Conflit"
  },
  {
    question: "Le liquidateur cherche à engager ma responsabilité pour faute de gestion (comblement passif).",
    despairLevel: "Total",
    answer: "C'est le cauchemar classique. Le droit anglais (Limited Liability) est beaucoup plus stricte sur la séparation des patrimoines. Il est extrêmement rare qu'un juge anglais autorise la saisie des biens personnels pour une dette commerciale, contrairement à la France.",
    targetAnchor: "rebound-vault?mode=liability",
    targetLabel: "Bloquer le Comblement"
  }
];

export interface ArticleData {
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  keywords: string[];
  category: "Fiscalité" | "Juridique" | "Banque" | "Patrimoine" | "Urgence" | "Performance" | "Stratégie" | "Expansion" | "Protection" | "Optimisation" | "Gestion" | "RH" | "Rémunération";
  relatedSlugs: string[];
  targetTool: 'calculator' | 'substance' | 'wealth' | 'optimizer' | 'banking' | 'scanner' | 'are' | 'shield' | 'salary' | 'nomad' | 'rebound' | 'expansion' | 'director-shield' | 'bureaucracy' | 'liquidation' | 'privacy' | 'bank-matchmaker' | 'fiscal-watch' | 'urssaf-tracker' | 'fixed-costs' | 'flat-tax' | 'rh-friction';
  targetAnchor: string;
  ctaText?: string;
}

export const ARTICLES: ArticleData[] = [
  // --- PROTECTION & URGENCE (1-10) ---
  { slug: "divorce-protection-parts-societe-uk", title: "Divorce : Protéger ses parts via Londres", category: "Protection", excerpt: "Isolation juridique contre le partage forcé. Pourquoi 2026 est l'année du verrouillage ?", targetTool: 'director-shield', targetAnchor: 'director-protection?mode=divorce', relatedSlugs: ["insaisissabilite-parts-sociales-londres"], keywords: ["Divorce", "Parts sociales"], content: "Un divorce peut anéantir 10 ans de travail acharné si vos parts de société sont incluses dans la masse partageable. En France, le régime de la communauté est un piège systémique pour l'entrepreneur.\n\n## La Frustration : Perdre 50% de sa boîte en une audience\n\nEn France, sans contrat de mariage blindé, la valeur de votre société créée pendant l'union tombe à 50% dans l'escarcelle de votre conjoint. Le juge peut forcer la vente des parts ou vous condamner à une prestation compensatoire délirante basée sur la valorisation théorique de votre business.\n\n> baromètre\n> Nos données 2025 révèlent qu'en France, 1 divorce d'entrepreneur sur 3 entraîne une vente forcée ou un endettement massif de la structure pour racheter les parts du conjoint.\n\n## La Solution : Le Firewall de la Common Law\n\nL'interposition d'une holding britannique (Limited) agissant comme propriétaire de vos structures françaises change radicalement la donne. En vertu de la Common Law, les titres de votre société UK sont régis par des 'Articles of Association' qui peuvent interdire contractuellement tout transfert de propriété non validé par le Board.\n\n- Inviolabilité territoriale : Vos parts sont liées à votre fonction de Director, pas à votre état civil.\n- Discrétion Territoriale : Le juge français a des difficultés majeures à évaluer et saisir des actifs régis par le droit anglais.\n- Protection de l'Héritage : Vous gardez le contrôle total de votre outil de production, indépendamment des aléas de votre vie privée.", ctaText: "Sécuriser mes Parts Sociales" },
  { slug: "insaisissabilite-parts-sociales-londres", title: "L'insaisissabilité réelle des parts Limited", category: "Protection", excerpt: "Pourquoi l'huissier français est impuissant face au droit anglais.", targetTool: 'director-shield', targetAnchor: 'director-protection?mode=seizure', relatedSlugs: ["divorce-protection-parts-societe-uk"], keywords: ["Saisie", "Common Law"], content: "Contrairement aux parts de SARL ou d'EURL françaises, qui peuvent être saisies par un simple huissier sur notification au greffe, les titres d'une Limited UK bénéficient de la souveraineté territoriale britannique.\n\n## La Frustration : Le clic qui bloque votre capital\n\nEn France, une créance personnelle peut se transformer en saisie de vos parts sociales en 48h. L'huissier informe le greffe, et vous ne pouvez plus vendre, fusionner ou lever des fonds. Votre capital est 'gelé'.\n\n> baromètre\n> Le nombre de saisies de parts sociales en France a bondi de 14,5% en 2024, suite au durcissement des procédures de recouvrement forcé post-PGE.\n\n## La Solution : 24 mois de répit juridique\n\nPour attaquer des parts britanniques, un créancier français doit d'abord obtenir l'exequatur de son jugement au Royaume-Uni. C'est une procédure internationale complexe, coûteuse et incertaine.\n\n- Inviolabilité territoriale : L'huissier français n'a aucun pouvoir au UK.\n- Charging Order vs Saisie : La Common Law privilégie souvent le maintien de l'activité plutôt que la vente forcée des titres.\n- Dissuasion par le coût : Engager une procédure internationale coûte souvent plus cher que la dette initiale, forçant le créancier à négocier.", ctaText: "Rendre mes Actifs Inattaquables" },
  { slug: "bouclier-atd-compte-bancaire-londres", title: "ATD : Le bouclier bancaire britannique", category: "Banque", excerpt: "Le fisc ne traverse pas la Manche. Sécurisez votre cash-flow.", targetTool: 'banking', targetAnchor: 'banking-shield?mode=atd', relatedSlugs: ["banque-uk-vs-offshore-resilience"], keywords: ["ATD", "Blocage"], content: "L'Avis de Tiers Détenteur (ATD), devenu Saisie Administrative (SATD), est l'arme atomique de l'administration fiscale française.\n\n## La Frustration : Compte bloqué en 24h sans juge\n\nEn un clic, le fisc gèle vos comptes personnels et professionnels. Plus de salaires, plus de fournisseurs, plus de loyer. Vous êtes mort financièrement avant même d'avoir pu contester la dette.\n\n> baromètre\n> La DGFiP a émis plus de 820 000 SATD en 2024-2025 pour apurer les passifs fiscaux. Personne n'est à l'abri d'une erreur administrative bloquante.\n\n## La Solution : L'immunité territoriale FCA\n\nCette prérogative régalienne s'arrête strictement aux frontières de l'Hexagone. Les banques britanniques, régies par la FCA, ne reconnaissent pas les notifications automatiques françaises.\n\n- Trésorerie de Réserve : Gardez votre cash de survie dans un IBAN GB hors de portée de Bercy.\n- Disponibilité Totale : Payez vos avocats et vos charges urgentes même en plein contrôle fiscal.\n- Sérénité Opérationnelle : Ne laissez pas une menace d'ATD dicter la gestion de votre entreprise.", ctaText: "Ouvrir mon Compte de Secours" },
  { slug: "abus-bien-social-directors-loan-account", title: "Abus de Bien Social : La souplesse UK", category: "Protection", excerpt: "Transformer un délit pénal en dette civile. Respirez enfin.", targetTool: 'director-shield', targetAnchor: 'director-protection?mode=social', relatedSlugs: ["divorce-protection-parts-societe-uk"], keywords: ["ABS", "Pénal"], content: "En France, la frontière entre votre argent et celui de la société est un champ de mines pénal.\n\n## La Frustration : 5 ans de prison pour une erreur de carte\n\nUtiliser la carte de la société pour une dépense perso, même remboursée, peut vous mener au tribunal pour Abus de Bien Social (ABS). En France, la 'confusion de patrimoine' est traitée comme un vol, avec des sanctions disproportionnées.\n\n> baromètre\n> Un audit de la situation financière 2024 montre que 92% des dirigeants de PME en liquidation subissent une enquête automatique pour abus de bien social.\n\n## La Solution : Le Director's Loan Account (DLA)\n\nLe cadre britannique est infiniment plus pragmatique. Le dirigeant peut légalement emprunter à sa structure via le 'Director's Loan Account'.\n\n- Cadre Civil vs Pénal : Ce qui est un délit en France est une simple créance comptable au UK.\n- Transparence Totale : Tout est tracé et régularisé via le bilan annuel, sans menace de prison.\n- Flexibilité de Style de vie : Gérez vos flux avec la souplesse d'une multinationale, validée par les standards IFRS.", ctaText: "Cadrer mon Director's Loan" },
  { slug: "rebond-apres-liquidation-judiciaire-france", title: "Rebond : Recréer son business après la faillite", category: "Urgence", excerpt: "Continuer son activité sans interruption. Le UK comme terre de résilience.", targetTool: 'rebound', targetAnchor: 'rebound-vault?mode=fiben', relatedSlugs: ["interdiction-gerer-france-solution-londres"], keywords: ["Liquidation", "Faillite"], content: "La liquidation d'une société française marque souvent la mort civile de son dirigeant. Mais votre talent n'est pas mort avec votre Kbis.\n\n## La Frustration : Le marquage au fer rouge (FIBEN)\n\nAprès une faillite, vous êtes fiché. Plus de compte pro, plus de prêt, plus de respectabilité. En France, on ne pardonne pas l'échec, on le punit pendant 5 à 10 ans.\n\n> baromètre\n> Selon nos études sur le rebond 2025, seuls 12% des entrepreneurs ayant fait faillite en France parviennent à relancer un projet viable dans les 3 ans à cause du blocage bancaire.\n\n## La Solution : Le 'Instant Rebound' Londonien\n\nLe Royaume-Uni voit l'échec comme une expérience. Londres permet de recréer une structure propre en 24h pour sauver vos contrats actifs.\n\n- Nouveau Départ : Une personnalité morale neuve, vierge de tout passif français.\n- Vitesse de Rétablissement : Immatriculez votre Limited et ouvrez une banque en ligne en un record de temps.\n- Continuité Client : Ne perdez pas vos contrats à cause d'une procédure technique en France. Transférez votre savoir-faire au UK.", ctaText: "Simuler mon Temps de Rebond" },
  { slug: "interdiction-gerer-france-solution-londres", title: "Interdiction de gérer : L'issue britannique", category: "Urgence", excerpt: "Les sanctions FR ne s'appliquent pas au UK. Reprenez le manche.", targetTool: 'rebound', targetAnchor: 'rebound-vault?mode=fiben', relatedSlugs: ["rebond-apres-liquidation-judiciaire-france"], keywords: ["Sanction", "Manager"], content: "Une interdiction de gérer est une condamnation qui vous exclut physiquement du marché du travail entrepreneurial en France.\n\n## La Frustration : La fin de votre carrière de dirigeant\n\nEn France, cette sanction vous interdit d'être gérant de droit ou de fait. C'est une 'mort professionnelle' qui vous condamne au salariat alors que vous avez l'âme d'un patron.\n\n> baromètre\n> En 2024, plus de 14 000 dirigeants ont été frappés d'interdiction de gérer en France. La plupart sont des victimes collatérales de liquidations complexes.\n\n## La Solution : La Souveraineté du Companies House\n\nLe registre britannique est indépendant. Sauf crimes internationaux, une sanction territoriale française ne vous empêche pas de diriger une Limited au UK.\n\n- Légalité Totale : Exercez votre métier de chef d'entreprise de manière légale dans une autre juridiction.\n- Preuve de Valeur : Gérez votre structure UK pour prouver votre capacité à réussir et générer des revenus.\n- Anticipation du Retour : Préparez votre avenir post-sanction avec un track-record international solide.", ctaText: "Activer mon Plan de Relance" },
  { slug: "protection-sci-urssaf-holding-uk", title: "Dettes URSSAF : Protéger sa maison via SCI", category: "Patrimoine", excerpt: "Rendre l'immobilier insaisissable. Le bouclier international.", targetTool: 'shield', targetAnchor: 'sci-shield', relatedSlugs: ["succession-heritage-holding-londres"], keywords: ["URSSAF", "Maison"], content: "Votre patrimoine immobilier est la cible numéro 1 des organismes de recouvrement. Si votre SCI est détenue en direct, elle est vulnérable.\n\n## La Frustration : L'huissier devant votre porte de famille\n\nL'URSSAF ou le Trésor Public peuvent saisir les parts de votre SCI française pour couvrir vos dettes pro. En quelques mois, votre résidence familiale ou votre investissement locatif peut être mis aux enchères.\n\n> baromètre\n> Les actions de recouvrement ciblant des actifs immobiliers via des saisies de parts de SCI ont bondi de 18% au premier trimestre 2025.\n\n## La Solution : Le Holding UK (Montage Cascade)\n\nTransférez la propriété des parts de votre SCI à une Limited UK. L'immeuble reste en France, mais son propriétaire est anglais.\n\n- Inaccessibilité Territoriale : Un créancier français doit engager une procédure complexe à Londres pour 'percer' une holding étrangère.\n- Protocole Dissuasif : Le coût et le délai d'une attaque internationale découragent 95% des recouvrements forcés.\n- Paix Familiale : Sécurisez votre toit avec une barrière de Common Law infranchissable.", ctaText: "Activer le Bouclier SCI" },
  { slug: "prudhommes-isoler-cash-execution-forcee", title: "Prud'hommes : Isoler son cash des salariés", category: "Protection", excerpt: "Éviter la saisie immédiate de votre trésorerie par l'exécution provisoire.", targetTool: 'director-shield', targetAnchor: 'director-protection?mode=blackmail', relatedSlugs: ["bouclier-atd-compte-bancaire-londres"], keywords: ["Prudhommes", "Cash"], content: "Un litige aux Prud'hommes peut déboucher sur une condamnation exécutoire à effet immédiat, souvent déconnectée de la réalité de votre trésorerie.\n\n## La Frustration : Payer avant même d'avoir pu faire appel\n\nEn France, les statistiques montrent un taux de condamnation des employeurs proche de 70%. L'exécution provisoire vous oblige à verser les indemnités immédiatement, même si vous contestez le jugement. Pour une PME, cela signifie souvent le dépôt de bilan immédiat par manque de cash.\n\n> baromètre\n> Le nombre de nouvelles affaires prud'homales a bondi en 2024-2025. Les délais de procédure explosent, bloquant vos provisions comptables pendant des années.\n\n## La Solution : Sanctuarisation via le Miroir UK\n\nEn isolant vos excédents de trésorerie dans une entité UK via des redevances ou des prestations réelles, vous rendez ce cash insaisissable par un huissier français.\n\n- Contrôle du Calendrier : Vous n'êtes plus l'esclave d'une procédure injuste ; vous négociez en position de force.\n- Protection de l'Exploitation : Votre cash-flow opérationnel reste à l'abri au UK, prêt à financer votre défense ou un accord raisonnable.\n- Dissuasion Juridique : L'exécution d'un jugement prud'homal sur des actifs britanniques est quasi-impossible sans une procédure internationale longue.", ctaText: "Désarmer le Chantage Salarié" },
  { slug: "audit-substance-defense-controle-fiscal", title: "Audit de Substance : Défendre son montage", category: "Fiscalité", excerpt: "Prouver la réalité économique à Londres. Zéro point d'accroche pour le fisc.", targetTool: 'substance', targetAnchor: 'substance-audit', relatedSlugs: ["etablissement-stable-requalification"], keywords: ["Fisc", "Substance"], content: "L'administration fiscale française tente systématiquement de requalifier les structures étrangères en 'sociétés de façade' si elle ne perçoit pas de substance économique locale.\n\n## La Frustration : Le redressement sur 'société fictive'\n\nAvoir une simple boîte aux lettres à Londres est suicidaire. Bercy utilise des logiciels de data-mining pour identifier les structures sans employés ou sans bureaux réels au UK, déclenchant des redressements automatiques à 25% d'IS + 80% de pénalités pour manœuvre frauduleuse.\n\n> baromètre\n> En 2025, la DGFiP a intensifié ses contrôles sur les montants de 'Management Fees' internationaux, avec un focus sur la hiérarchie de décision effective (Mind and Management).\n\n## La Solution : Architecture de Substance Certifiée\n\nNous auditons votre montage selon les critères de la jurisprudence 'Cadbury Schweppes' pour garantir que votre Limited est inattaquable.\n\n- Preuve de Vie Économique : Bureaux réels, directeurs locaux et procès-verbaux de board datés et localisés au UK.\n- Validité des Flux : Justification chirurgicale de chaque euro remonté au UK via des prestations réelles.\n- Sécurité Totale : Transformez votre suspicion de fraude en une stratégie d'optimisation légitime et documentée dès le premier jour.", ctaText: "Lancer mon Audit de Substance" },
  { slug: "etablissement-stable-requalification", title: "Établissement Stable : Éviter le piège", category: "Fiscalité", excerpt: "Rester hors radar du fisc français. Pilotez votre structure sans risque.", targetTool: 'substance', targetAnchor: 'substance-audit', relatedSlugs: ["audit-substance-defense-controle-fiscal"], keywords: ["IS", "CGI"], content: "Le risque d'établissement stable est le cauchemar de l'expatrié fiscal ou de l'entrepreneur nomade gérant une structure étrangère.\n\n## La Frustration : L'IS français sur vos profits mondiaux\n\nSi vous gérez votre Limited UK depuis votre salon en France sans précautions, Bercy considérera que le siège de direction effective est en France. Conséquence : 25% d'IS rétroactif sur l'ensemble de votre chiffre d'affaires mondial d'un seul coup.\n\n> baromètre\n> Les requalifications en 'Établissement Stable' ont augmenté de 22% en un an grâce au croisement des données bancaires internationales (CRS) et des profils LinkedIn.\n\n## La Solution : Cloisonnement Chirurgical\n\nL'arbitrage fiscal est un art qui nécessite de la rigueur chirurgicale dans la séparation des flux et des centres de décision.\n\n- Gouvernance UK : Validation des décisions stratégiques par un directeur résident UK.\n- Signature Contractuelle : Vos contrats clients doivent être signés et gérés depuis la juridiction britannique.\n- Digital Nomadism Cadré : Gérez votre structure internationale sans jamais déclencher la territorialité fiscale française grâce à nos process de conformité 2026.", ctaText: "Bloquer ma Requalification ES" },

  // --- PERFORMANCE & CASH (11-25) ---
  { slug: "arbitrage-fiscal-2025-is-19-vs-25", title: "Optimisation 2026 : IS 19% vs 25%", category: "Performance", excerpt: "Gagner 6% de marge nette immédiatement. Pourquoi attendre ?", targetTool: 'calculator', targetAnchor: 'simulator', relatedSlugs: ["calculator-sasu-vs-limited"], keywords: ["Impôts", "Bénéfice"], content: "La pression fiscale en France reste l'une des plus étouffantes au monde pour les PME en croissance.\n\n## La Frustration : 1/4 de vos bénéfices part en IS\n\nEn France, l'Impôt sur les Sociétés (IS) standard à 25% ponctionne vos ressources avant même que vous ne puissiez réinvestir. Sur 100 000€ de bénéfices, vous perdez 25 000€ que vos concurrents anglo-saxons gardent en trésorerie.\n\n> baromètre\n> Le différentiel fiscal entre la France et le UK permet à une Limited de réinvestir 6 000€ de plus par an dès le premier euro de bénéfice par rapport à une SASU.\n\n## La Solution : Levier de Croissance Immédiat\n\nLe Royaume-Uni maintient sa Corporation Tax attractive à 19% pour les petites entreprises (Small Profits Rate) jusqu'en 2026.\n\n- Trésorerie boostée : Un gain de 6% de marge nette transformable en budget pub ou recrutement.\n- Réinvestissement Brut : Capitalisez plus vite au sein de votre structure pour préparer votre exit.\n- Saine Gestion : L'arbitrage fiscal n'est pas une fraude, c'est le devoir de tout dirigeant de protéger la rentabilité de son entreprise.", ctaText: "Calculer mon Économie d'IS" },
  { slug: "calculator-sasu-vs-limited", title: "Match : SASU vs Limited (Le Chiffre)", category: "Fiscalité", excerpt: "Comparatif financier après taxes et dividendes.", targetTool: 'calculator', targetAnchor: 'simulator', relatedSlugs: ["arbitrage-fiscal-2025-is-19-vs-25"], keywords: ["Match", "Net"], content: "Pour un entrepreneur résident français, la question n'est pas seulement l'IS, mais le 'disponible personnel net' après dividendes. En France, après 25% d'IS et 30% de Flat Tax, il reste environ 52,5% du profit initial. Au Royaume-Uni, malgré la Corporation Tax et l'impôt sur les dividendes (ou la Flat Tax en France lors du rapatriement), le montage 'Limited' permet d'optimiser les charges sociales et les abattements spécifiques. Le résultat est souvent sans appel : un gain de 15% à 25% de cash net disponible supplémentaire chaque année. Ne naviguez plus à vue, simulez votre gain réel en fonction de votre chiffre d'affaires et de vos charges d'exploitation.", ctaText: "Comparer SASU vs Limited" },
  { slug: "salary-dividend-mix-optimal", title: "Salaire vs Dividende : Le mix parfait 2026", category: "Performance", excerpt: "Optimiser son net sans sacrifier sa retraite. Le modèle hybride.", targetTool: 'salary', targetAnchor: 'salary-optimizer', relatedSlugs: ["cumul-are-pole-emploi-capitalisation-uk"], keywords: ["Salaire", "Mix"], content: "Être 'Director' d'une Limited offre une liberté totale dans le mode de rémunération, mais naviguer entre charges sociales et impôt sur le revenu est un art.\n\n## La Frustration : 45% de charges sociales en SASU\n\nEn France, vous êtes 'assimilé salarié'. Pour vous verser 5 000€ net, votre société doit débourser environ 9 000€. Près de la moitié de votre effort part dans un système social dont vous ne verrez les bénéfices que dans 30 ans, si le système survit.\n\n> OBSERVATOIRE\n> Nos simulations 2026 montrent qu'un dirigeant de SASU paie en moyenne 28 000€ de 'sur-charges' sociales par an par rapport à un Director UK pour un revenu net équivalent.\n\n## La Solution : Le Mix Hybride BritFlow\n\nLa stratégie consiste à fixer un salaire 'Seuil' (Secondary Threshold) au UK qui évite les charges patronales tout en validant vos droits sociaux (National Insurance).\n\n- Optimisation Dividendes : Le surplus de profit est distribué en dividendes avec un impôt réduit (8.75% au premier niveau).\n- Protection de Standing : Validez vos trimestres de retraite internationale et votre couverture santé sans payer le prix fort du système français.\n- Liberté de Flux : Ajustez votre rémunération chaque mois en fonction de votre trésorerie réelle, sans la rigidité du bulletin de paie français.", ctaText: "Optimiser mon Salaire UK" },
  { slug: "facturation-usa-w8ben-convention-uk", title: "USA : Facturer via Londres (Convention UK-US)", category: "Expansion", excerpt: "Réduire les retenues à la source US à 0%. L'avantage compétitif.", targetTool: 'expansion', targetAnchor: 'expansion-hub', relatedSlugs: ["tresorerie-multi-devises-dollar-wise"], keywords: ["USA", "Export"], content: "Facturer le marché américain est le rêve de tout solopreneur Tech ou Agence, mais le 'Withholding Tax' peut transformer ce rêve en cauchemar fiscal.\n\n## La Frustration : 30% amptutés par l'IRS\n\nSi vous facturez des clients US depuis la France, vous risquez une retenue à la source automatique de 30% sur vos factures de services ou de royalties si votre formulaire W8-BEN-E n'est pas parfait. Récupérer cet argent auprès de l'IRS est un enfer administratif de plusieurs années.\n\n> OBSERVATOIRE\n> Selon les données de l'Atlantic Declaration (2024-2025), les flux commerciaux UK-US bénéficient d'une priorité de traitement bancaire et fiscale, réduisant les délais de compliance de 40%.\n\n## La Solution : Le Pont Transatlantique Londonien\n\nLe Royaume-Uni dispose de la convention fiscale la plus robuste au monde avec les USA.\n\n- Retenue à 0% : En facturant via votre Limited UK, vous tombez souvent à 0% de retenue à la source sur les services et les royalties.\n- Crédibilité Stripe/PayPal : Vos comptes de paiement US sont validés instantanément car ils reconnaissent la juridiction de la City.\n- Expansion Facilitée : Londres est l'endroit idéal pour recréer une entité miroir (Delaware Flip) si vous levez des fonds aux USA plus tard.", ctaText: "Simuler ma Croissance USA" },
  { slug: "ecommerce-tva-brexit-londres", title: "E-commerce : Le Hub Fiscal de Londres en 2026", category: "Performance", excerpt: "Optimiser ses flux mondiaux via le seuil de TVA à £90k. Pourquoi 2026 est l'année du pivot stratégique ?", targetTool: 'calculator', targetAnchor: 'obs/tva', relatedSlugs: ["facturation-usa-w8ben-convention-uk"], keywords: ["TVA", "Drop", "Brexit"], content: "En 2026, le paysage du e-commerce mondial a radicalement changé. Alors que l'Union Européenne durcit ses contrôles via l'IOSS et les seuils de vente à distance, le Royaume-Uni s'affirme comme le 'Safe Haven' fiscal pour les commerçants digitaux.\n\n## La Frustration : Le 'TVA Shock' qui dévore vos marges\n\nEn France, le seuil de franchise en base de TVA pour les services et le dropshipping reste bloqué à seulement 37 500€. Dès l'euro suivant, vous passez d'une marge brute de 100% à 80% car vous devez collecter 20% pour l'État sans pouvoir augmenter vos prix face à la concurrence internationale.\n\n> OBSERVATOIRE\n> Selon nos analyses 2025, un e-commerçant réalisant 100 000€ de chiffre d'affaires au Royaume-Uni génère 20 000€ de cash net supplémentaire par rapport à son homologue français, uniquement grâce à l'écart des seuils (90k£ vs 37k€).\n\n## La Solution : Levier de Capitalisation via le Hub UK\n\nLe Royaume-Uni a confirmé le maintien du seuil de registration à £90,000 (env. 105 000€) jusqu'en mars 2026. Cette 'bulle de croissance' permet aux structures agiles d'accumuler du trésor de guerre.\n\n| Performance 2026 | France (SASU) | UK (Limited) |\n| :--- | :--- | :--- |\n| Seuil de registration | 37 500€ | ~105 000€ (£90k) |\n| Perte de marge immédiate | -20% (dès 37k€) | 0% (jusqu'à 105k€) |\n| Déductibilité Publicité | Complexe | 100% Pre-tax |\n| Agilité IOSS | Friction administrative | Native & Digitale |\n\n## Pourquoi 2026 est l'année du pivot ?\n\nAvec l'explosion des coûts d'acquisition sur Meta et Google (CPM +22% en un an), la survie d'un business digital ne se joue plus sur le marketing, mais sur l'arbitrage fiscal. \n\nUtiliser une Limited UK n'est plus un 'hack', c'est l'assurance-vie de votre business modèle. Ne laissez pas Bercy prendre 20% de votre chiffre d'affaires avant même que vous n'ayez pu payer vos premiers prestataires.", ctaText: "Maximiser mes Marges E-com" },
  { slug: "banque-uk-vs-offshore-resilience", title: "Banque UK vs Offshore : Le match de la respectabilité", category: "Banque", excerpt: "HSBC/Barclays vs Dubaï/Maurice. Pourquoi l'offshore vous tuera.", targetTool: 'banking', targetAnchor: 'banking-shield', relatedSlugs: ["bouclier-atd-compte-bancaire-londres"], keywords: ["Banque", "KYC"], content: "L'erreur fatale de l'optimiseur débutant est de confondre '0% d'impôt' et 'liberté bancaire'.\n\n## La Frustration : L'alerte rouge Tracfin sur l'exotisme\n\nOuvrir un compte à Dubaï, Maurice ou aux Seychelles est devenu un signal d'alarme pour les banques européennes. Vos virements vers vos fournisseurs sont bloqués, vos clients hésitent à payer sur des comptes 'à risque', et vous passez votre vie à répondre à des questionnaires KYC interminables.\n\n> OBSERVATOIRE\n> En 2025, le taux de clôture arbitraire de comptes 'Offshore' par les banques de détail européennes a augmenté de 35% par simple mesure de précaution réglementaire.\n\n## La Solution : La Place Financière n°1 Mondiale\n\nLondres offre une alternative souveraine : une place financière prestigieuse, respectée par tous les régulateurs mondiaux.\n\n- Respectabilité Bancaire : Une banque britannique (Barclays, Lloyds, Revolut Business) est un gage de sérieux pour vos partenaires.\n- Fluidité SEPA : Encaissez vos clients européens sans frottement et sans suspicion de blanchiment.\n- Sécurité des Dépôts : Bénéficiez de la protection du FSCS britannique, bien plus solide que les garanties des paradis fiscaux exotiques.", ctaText: "Choisir ma Banque UK Respectable" },
  { slug: "tresorerie-multi-devises-dollar-wise", title: "Trésorerie Dollar : Encaisser $ sans frais", category: "Banque", excerpt: "Gestion native multi-devises au UK. Évitez les 3% de perte au change.", targetTool: 'banking', targetAnchor: 'banking-shield', relatedSlugs: ["facturation-usa-w8ben-convention-uk"], keywords: ["Forex", "Dollar"], content: "Si votre business facture en Dollars mais que vos coûts sont en Euros, vous payez une taxe invisible et massive au milieu.\n\n## La Frustration : La ponction silencieuse du Forex\n\nLes banques traditionnelles françaises prennent entre 2% et 5% de commission sur chaque conversion Dollar/Euro. Sur 100 000$ de CA, c'est 5 000€ qui s'évaporent simplement pour avoir le droit d'utiliser votre argent en Europe.\n\n> OBSERVATOIRE\n> Un entrepreneur US-centrique économise en moyenne 4 200€ de frais de change par an en basculement sur une gestion de trésorerie native à Londres via Wise / Revolut.\n\n## La Solution : Le Hub de Devises de la City\n\nLondres est le centre mondial du Forex. Les banques et fintechs UK offrent des comptes multi-devises natifs avec des taux interbancaires réels.\n\n- Comptes US Locaux : Encaissez via un ACH/Routing number comme si vous étiez à New York.\n- Zéro Friction : Payez vos prestataires mondiaux ou vos serveurs AWS directement en $ sans conversion.\n- Arbitrage de Change : Convertissez vos fonds seulement quand le taux est favorable, pas quand votre banque vous l'impose.", ctaText: "Blindager ma Trésorerie Dollar" },
  { slug: "achat-voiture-luxe-societe-uk-advantage", title: "Véhicules de luxe : L'avantage BIK UK 2026", category: "Patrimoine", excerpt: "Rouler en prestige via sa Limited. L'écologie qui rapporte.", targetTool: 'director-shield', targetAnchor: 'director-protection?mode=perks', relatedSlugs: ["abus-bien-social-directors-loan-account"], keywords: ["Prestige", "BIK"], content: "Acheter un véhicule haut de gamme sur sa société française est devenu une aberration fiscale.\n\n## La Frustration : TVS punitive et Malus record\n\nEn France, le malus écologique peut atteindre 60 000€, et la TVS (Taxe sur les Véhicules de Société) est une ponction annuelle récurrente. De plus, l'avantage en nature (TVN) est taxé à l'impôt sur le revenu à des taux confiscatoires.\n\n> OBSERVATOIRE\n> En 2026, posséder un véhicule premium de type Porsche Taycan ou Tesla Model S Plaid au nom d'une SASU française coûte 3x plus cher en taxes qu'au sein d'une Limited UK.\n\n## La Solution : Le Benefit in Kind (BIK) à 4%\n\nLe Royaume-Uni a mis en place un barème clair et ultra-incitatif pour les véhicules à faibles émissions.\n\n- BIK Réduit : Le taux d'avantage en nature pour un véhicule électrique est fixé à seulement 4% pour 2026, là où la France l'évalue sur le prix fort.\n- Zéro Malus UK : Achetez votre véhicule de prestige sans la taxe 'punitive' française à l'immatriculation.\n- Discrétion Totale : Le véhicule est immatriculé au nom de votre entité britannique, dissociant votre passion du luxe de votre visibilité fiscale personnelle.", ctaText: "Activer mon Bouclier Dirigeant" },
  { slug: "crypto-actifs-societe-uk-capitalisation", title: "Crypto : Gérer ses actifs via Limited UK", category: "Performance", excerpt: "Détention pro sans Flat Tax personnelle. Le Hub Crypto 2026.", targetTool: 'wealth', targetAnchor: 'wealth-audit?mode=crypto', relatedSlugs: ["tresorerie-multi-devises-dollar-wise"], keywords: ["Crypto", "BTC"], content: "Le régime fiscal français sur les plus-values de crypto-actifs est une barrière majeure à la capitalisation.\n\n## La Frustration : Chaque trade est un mur fiscal\n\nEn France, la Flat Tax de 30% s'applique dès que vous repassez en Stablecoin ou en Fiat. Impossible de 'compounder' efficacement vos gains. Pire, une activité trop intense peut vous requalifier en trader pro avec un impôt grimpant à 45%.\n\n> OBSERVATOIRE\n> Le Royaume-Uni a finalisé en 2025 sa réglementation 'Crypto Hub', offrant un cadre comptable clair pour les entreprises et facilitant l'ouverture de comptes exchange Corporate.\n\n## La Solution : Le Capital-Trading Professionnel\n\nEn logeant votre portefeuille au sein d'une Limited UK, vous passez d'une fiscalité personnelle subie à une gestion d'actifs pro.\n\n- Report d'Imposition : Vos gains sont réinvestis instantanément au sein de la structure sans impôt personnel. Vous ne payez l'IS (19%) qu'en fin d'année sur le bénéfice net.\n- Déductibilité des Outils : Vos abonnements de trading, vos hardwares wallets et vos formations sont des charges déductibles.\n- Respectabilité Institutionnelle : Accédez aux versions 'Pro' des plus grands exchanges mondiaux avec la légitimité d'une société de droit anglais.", ctaText: "Capitaliser mes Crypto en Limited" },
  { slug: "holding-ip-marques-strategie", title: "Holding IP : Protéger ses marques au UK", category: "Performance", excerpt: "Isoler l'actif immatériel de l'opérationnel. Pourquoi 2026 est crucial.", targetTool: 'optimizer', targetAnchor: 'optimization', relatedSlugs: ["royalties-refacturation-ip-marge-shift"], keywords: ["Marque", "Brevet"], content: "Dans le business moderne, la valeur n'est pas dans le stock, mais dans l'immatériel.\n\n## La Frustration : L'actif stratégique otage de l'URSSAF\n\nSi votre marque ou votre domaine est logé dans votre société opérationnelle française, ils sont vulnérables en cas de saisie, de litige social ou de liquidation. Vous pouvez perdre le contrôle de votre identité commerciale du jour au lendemain.\n\n> OBSERVATOIRE\n> En 2024, le rachat de marques 'aux enchères' après liquidation judiciaire a bondi au profit de fonds de retournement, dépouillant les fondateurs de leur création.\n\n## La Solution : Le Coffre-Fort de la City\n\nIsolez vos actifs 'Intellectual Property' (IP) dans une holding dédiée à Londres.\n\n- Sanctuaire Juridique : Votre marque est la propriété d'une entité britannique inattaquable par les créanciers français.\n- Revenus de Location : Percevez des royalties pour l'usage de votre marque, optimisant votre cash-flow au UK à 19% d'IS.\n- Prêt pour le Scale : Une holding UK facilite les licences internationales et la revente (Exit) de vos actifs immatériels à des acteurs mondiaux.", ctaText: "Isoler ma Marque au UK" },
  { slug: "succession-heritage-holding-londres", title: "Succession : Transmettre via le Trust ou FIC UK", category: "Patrimoine", excerpt: "Éviter les 45% de droits de succession FR. Protégez votre descendance.", targetTool: 'wealth', targetAnchor: 'wealth-audit?mode=inheritance', relatedSlugs: ["protection-sci-urssaf-holding-uk"], keywords: ["Héritage", "Trust"], content: "La France possède l'un des régimes de succession les plus confiscatoires au monde, taxant l'effort d'une vie au profit de l'État.\n\n## La Frustration : 45% de votre travail s'évapore au décès\n\nEntre parents et enfants, les droits de succession peuvent grimper jusqu'à 45%. Pour un entrepreneur, cela signifie souvent que les héritiers doivent vendre l'entreprise ou s'endetter lourdement pour simplement payer l'impôt sur le patrimoine que vous avez déjà bâti.\n\n> OBSERVATOIRE\n> En 2024-2025, le rendement des droits de succession en France a atteint un record de 17 milliards d'euros, illustrant la pression fiscale croissante sur la transmission du capital.\n\n## La Solution : La Family Investment Company (FIC)\n\nUtilisez la flexibilité du droit anglo-saxon pour organiser la transmission de manière progressive et fiscalement neutre.\n\n- Contrôle vs Propriété : Gardez la gestion de vos actifs tout en transmettant la valeur future (Growth Shares) à vos enfants.\n- Discrétion de Transmission : Les règles de Common Law permettent des montants de transmission bien plus souples que le carcan rigide du code civil français.\n- Pérennité de l'Outil : Garantissez que votre empire financier reste entre les mains de votre famille, intact et capitalisé.", ctaText: "Sécuriser mon Héritage" },
  { slug: "management-fees-justification-fiscale", title: "Management Fees : Justifier ses flux 2026", category: "Performance", excerpt: "Rendre les flux inter-sociétés inattaquables. Dormez tranquille en cas d'audit.", targetTool: 'optimizer', targetAnchor: 'optimization', relatedSlugs: ["audit-substance-defense-controle-fiscal"], keywords: ["Fees", "Audit"], content: "La refacturation de 'Management Fees' est l'outil n°1 pour remonter des profits tout en diminuant l'IS en France.\n\n## La Frustration : L'acte anormal de gestion\n\nBercy scrute ces flux à la loupe. Si vos factures de management vers Londres ne sont pas documentées ou si le tarif semble arbitraire, le fisc français peut réintégrer 100% des sommes dans votre bénéfice taxable et ajouter 40% de pénalités pour manœuvre frauduleuse.\n\n> OBSERVATOIRE\n> Le Plan de Lutte contre la Fraude 2026 prévoit des audits automatisés sur les holdings sans substance effectuant des remontées de fees supérieures à 15% du CA opérationnel.\n\n## La Solution : Convention de Management Certifiée\n\nNous vous accompagnons dans la création d'un dossier de défense inattaquable.\n\n- Réalité de la Prestation : Rédaction de contrats-cadres détaillant les services de direction, support IT, finance ou marketing global fournis par le UK.\n- Prix de Transfert : Fixation de tarifs 'pleine concurrence' (Arm's Length) conformes aux directives de l'OCDE.\n- Traçabilité Chirurgicale : Procès-verbaux de board et rapports d'activité prouvant la valeur ajoutée réelle du pôle londonien.", ctaText: "Optimiser mes Management Fees" },
  { slug: "controle-fiscal-personnel-esfp-preparation", title: "ESFP : Se préparer au contrôle personnel", category: "Fiscalité", excerpt: "Expliquer son train de vie via le UK.", targetTool: 'scanner', targetAnchor: 'scanner?mode=lifestyle', relatedSlugs: ["abus-bien-social-directors-loan-account"], keywords: ["ESFP", "Fisc"], content: "L'Examen de Situation Fiscale Personnelle (ESFP) est le contrôle le plus intrusif : le fisc épluche vos relevés bancaires perso pour vérifier si votre train de vie 'colle' à vos revenus déclarés. Si vous vivez de dividendes britanniques ou que vous utilisez un Director's Loan UK, vous devez être capable de justifier l'origine des fonds avec une rigueur absolue. La structure Limited UK, si elle est gérée selon les standards britanniques, fournit toute la documentation nécessaire pour prouver que les flux ne sont pas occultes mais issus d'une activité internationale régulière. Anticipez le contrôle en mettant de l'ordre dans votre architecture fiscale dès aujourd'hui.", ctaText: "Justifier mon Train de Vie" },

  // --- NOUVEAUX GAPS SEO (Gaps Low-Compétition) ---
  { slug: "micro-entrepreneur-passage-ltd-uk-guide", title: "Micro-Entrepreneur → LTD UK : Le Saut Quantique", category: "Stratégie", excerpt: "Quitter l'auto-entreprise pour la puissance du UK. Guide 7 Jours.", targetTool: 'calculator', targetAnchor: 'simulator', relatedSlugs: ["arbitrage-fiscal-2025-is-19-vs-25"], keywords: ["Micro", "Auto-entrepreneur"], content: "Le statut de micro-entrepreneur est fantastique pour démarrer. Mais c'est un piège à croissance dès que votre talent explose.\n\n## La Frustration : Payer plus de cotisations que vous ne gagnez de bénéfice\n\nEn micro, vous payez ~22% sur votre chiffre d'affaires, pas sur votre profit. Si vous avez 30% de charges (logiciels, pub, freelances), votre taux d'imposition réel sur le bénéfice bondit à plus de 40%. Vous travaillez pour l'URSSAF, pas pour vous.\n\n> OBSERVATOIRE\n> Selon nos baromètres 2026, un freelance réalisant 70k€ de CA gagne 14 500€ de cash net de plus par an en Limited UK qu'en micro-entreprise française.\n\n## La Solution : Migration en 7 Jours\n\nTransformez votre activité de 'freelance bricoleur' en 'entreprise internationale'.\n\n- Zéro Plafond : Ne freinez plus vos factures pour rester sous les seuils de franchise.\n- Déductibilité Totale : Déduisez 100% de vos frais réels (Meta Ads, abonnements IA, voyages pro) avant tout impôt.\n- Prestige et Scale : Présentez-vous comme une Limited de droit anglais, inspirant confiance à vos clients mondiaux.", ctaText: "Simuler mon Gain Net" },
  { slug: "compte-bancaire-ltd-uk-resident-francais-wise", title: "Comptes UK pour Français 2026 : Le Guide", category: "Banque", excerpt: "Ouvrir un compte business UK sans voyager. Wise vs HSBC.", targetTool: 'bank-matchmaker', targetAnchor: 'obs/banques', relatedSlugs: ["banque-uk-vs-offshore-resilience"], keywords: ["Compte", "Wise"], content: "L'ouverture d'un compte bancaire est le dernier verrou de votre expansion. En 2026, la technologie a aboli les frontières.\n\n## La Frustration : Le refus automatique des banques locales\n\nLes banques de détail françaises sont de plus en plus frileuses face aux structures internationales. 'Compliance alambiquée', délais de 3 mois, et refus sans motif sont devenus la norme pour les entrepreneurs audacieux.\n\n> OBSERVATOIRE\n> En 2025, le délai moyen d'ouverture d'un compte professionnel 'international' dans une banque traditionnelle française a atteint 82 jours, contre 48h au Royaume-Uni.\n\n## La Solution : Le Multi-Banquing Digital\n\nNe laissez plus une banque française vous tenir en otage. Diversifiez votre trésorerie sur un IBAN 'GB' insaisissable.\n\n- IBAN GB à Distance : Des solutions comme Wise, Revolut Business ou Tide ouvrent votre compte en 48h avec une simple pièce d'identité.\n- Nativement Multi-Devises : Encaissez en £, $ et € sans commissions de change cachées.\n- Respectabilité de la City : Obtenez des cartes bancaires Corporate prestigieuses et acceptées mondialement sans limite de plafond arbitraire.", ctaText: "Obtenir mon IBAN GB à Distance" },
  { slug: "freelance-it-ltd-uk-vs-portage-ir35", title: "Freelance IT : LTD UK vs Portage (Gain 32% Net)", category: "Performance", excerpt: "Gagner 30% de plus qu'en portage salarial. Pourquoi se brider ?", targetTool: 'calculator', targetAnchor: 'simulator', relatedSlugs: ["recrutement-global-talent-international"], keywords: ["Freelance", "IT"], content: "Le portage salarial est souvent présenté comme la sécurité. C'est surtout une ponction massive sur votre talent.\n\n## La Frustration : 50% de votre TJM part en 'frais'\n\nEn France, après commission de portage, cotisations patronales et salariales, il ne vous reste souvent que 48% de ce que votre client paie réellement. Vous financez un système social dont vous n'avez pas besoin en tant que digital-nomad ou expert Tech.\n\n> OBSERVATOIRE\n> Pour un TJM de 600€, l'écart de disponible net après IS et Flat Tax entre le portage français et la Limited UK est de 2 100€ de cash supplémentaire par mois.\n\n## La Solution : La Structure B2B Internationale\n\nLa Limited UK est l'alternative royale pour les développeurs, DevOps et consultants Tech.\n\n- Indépendance Totale : Facturez vos clients (souvent US ou internationaux) en direct, sans intermédiaire coûteux.\n- Déduction des Frais Tech : Votre MacBook Pro, votre setup 49 pouces et vos serveurs cloud sont déduits à 100% de votre profit taxable.\n- Conformité IR35 : Nos contrats incluent des clauses de substitution et d'équipement propre, validant votre statut B2B réel face au fisc anglais et français.", ctaText: "Comparer Portage vs LTD" },
  { slug: "sci-francaise-holding-londres-montage", title: "SCI Française + Holding Londres : Le Montage Ultime", category: "Patrimoine", excerpt: "Verrouiller votre immobilier français depuis Londres. Adieu URSSAF.", targetTool: 'shield', targetAnchor: 'sci-shield', relatedSlugs: ["protection-sci-urssaf-holding-uk"], keywords: ["SCI", "Montage"], content: "La SCI détenue en direct est une proie facile pour les organismes de recouvrement. Voici comment la transformer en forteresse.\n\n## La Frustration : Votre maison comme caution pro\n\nSi vous êtes en SASU ou Freelance, une mauvaise année peut mener l'URSSAF à saisir vos parts de SCI. En un instant, votre patrimoine immobilier durement acquis sert à éponger des dettes administratives.\n\n> OBSERVATOIRE\n> Les procédures de 'Saisie de Parts de SCI' pour dettes sociales professionnelles ont augmenté de 18% en 2024, devenant le levier n°1 de recouvrement forcé en France.\n\n## La Solution : Le Verrouillage International\n\nLe montage 'Holding UK mère de SCI' change la nationalité du propriétaire fiscal sans déménager l'immeuble.\n\n- Inaccessibilité des Parts : L'huissier français ne peut pas saisir des parts appartenant à une société étrangère sans une procédure d'exequatur prohibée par son coût.\n- Discrétion de Détention : Vos actifs immobiliers sortent du radar des recherches automatiques de patrimoine des créanciers français.\n- Optimisation des Flux : Remontez la trésorerie de votre SCI vers votre Holding UK pour réinvestir mondialement en minimisant les frottements fiscaux.", ctaText: "Sécuriser ma SCI" },
  { slug: "exit-tax-france-ltd-uk-bouclier", title: "Exit Tax France : LTD UK comme Bouclier 2026", category: "Stratégie", excerpt: "Désamorcer l'Exit Tax AVANT votre départ. Sécurisez votre plus-value.", targetTool: 'nomad', targetAnchor: 'nomad-scanner', relatedSlugs: ["exit-tax-france-eviter-le-piege"], keywords: ["Exit Tax", "Expatriation"], content: "L'Exit Tax est le 'mur de Berlin' fiscal français. Elle fige votre imposition sur les plus-values latentes au moment où vous quittez l'Hexagone.\n\n## La Frustration : 30% de votre boîte 'confisqués' au départ\n\nSi votre société vaut 1M€, Bercy peut exiger un paiement ou une caution de 300 000€ pour vous autoriser à déplacer votre résidence fiscale. C'est un boulet financier qui paralyse votre mobilité internationale.\n\n> OBSERVATOIRE\n> Nos analyses de mobilité 2025 montrent qu'un entrepreneur sur quatre retarde son expatriation de plus de 18 mois à cause de l'incertitude sur le calcul de l'Exit Tax.\n\n## La Solution : Le Sursis via la Holding UK\n\nTransférer vos titres à une Holding britannique AVANT l'explosion de la valorisation et le départ effectif.\n\n- Gel de la Valorisation : Fixez le point de départ de votre taxe sur une base maîtrisée.\n- Substance Économique UK : Créez une réalité opérationnelle à Londres pour justifier le montage et bénéficier du sursis d'imposition.\n- Liberté Mondiale : Déplacez-vous au UK, à Dubaï ou ailleurs avec une structure holding prestigieuse qui gère vos participations sans les entraves administratives françaises.", ctaText: "Scanner mon Risque Exit" },

  // --- CRYPTO & DEFI (2026 GAPS) ---
  { slug: "staking-defi-via-societe-uk-fiscalite", title: "Staking & DeFi : Optimiser les Yields au UK", category: "Performance", excerpt: "Faire fructifier ses stablecoins sans friction. Le Hub DeFi 2026.", targetTool: 'wealth', targetAnchor: 'wealth-audit?mode=crypto', relatedSlugs: ["declaration-crypto-ltd-uk-resident-francais-gains"], keywords: ["DeFi", "Staking"], content: "Les revenus de Staking ou de Liquidity Farming sont un défi comptable et fiscal majeur en France.\n\n## La Frustration : L'incertitude du régime BNC vs RCM\n\nEn France, le flou juridique sur la nature des revenus DeFi (Bénéfices Non Commerciaux ou Revenus de Capitaux Mobiliers) expose l'investisseur à une requalification arbitraire lors d'un contrôle. L'asphyxie administrative tue votre rendement.\n\n> baromètre\n> Le Royaume-Uni a mis en place en 2025 les directives 'DeFi Taxation Safe Harbor', simplifiant la déclaration des smart-contracts pour les entreprises.\n\n## La Solution : Le Hub DeFi Londonien\n\nEn logeant votre trésorerie DeFi dans une structure UK, vous bénéficiez d'un cadre réglementaire stable et pro-innovation.\n\n- Simplification Comptable : Les yields sont traités comme du chiffre d'affaires classique de la Limited, déductibles de vos frais de recherche.\n- Réinvestissement 100% Brut : Faites fructifier vos stablecoins sans ponction fiscale sur chaque distribution de récompenses.\n- Souveraineté des Fonds : Vos actifs sont détenus par une entité régie par la Common Law, offrant une protection supérieure en cas de faillite de plateforme.", ctaText: "Auditer ma Trésorerie DeFi" },

  // --- NOMADES & IA FREELANCE ---
  { slug: "digital-nomad-francais-ltd-uk-residence-183-jours", title: "Digital Nomad : La Règle des 183 Jours 2.0", category: "Stratégie", excerpt: "Ne restez pas résident fiscal français par erreur. L'audit OECD 2026.", targetTool: 'nomad', targetAnchor: 'nomad-scanner', relatedSlugs: ["nomadisme-digital-residence-fiscale-audit"], keywords: ["Nomad", "Voyage"], content: "Vivre en nomade ne signifie pas être invisible fiscalement. L'échange automatique d'informations (CRS 2.0) a changé la donne.\n\n## La Frustration : Le retour de manivelle du fisc français\n\nSi vous voyagez sans port d'attache clair, Bercy peut revendiquer votre résidence fiscale dès lors que vous gardez une carte bancaire, une famille ou des clients en France. Vous risquez un redressement sur l'intégralité de vos revenus mondiaux des 3 dernières années.\n\n> baromètre\n> Le croisement des données de géo-localisation et des flux bancaires internationaux permet désormais au fisc de détecter les 'faux expatriés' en moins de 12 mois.\n\n## La Solution : Le Hub de Résidence Administrative UK\n\nÉtablissez votre centre d'intérêts économiques au UK via une Limited et une adresse de correspondance réelle.\n\n- Preuve de Substance : Justifiez que votre business est piloté depuis Londres, créant une barrière de protection contre l'article 4B du CGI français.\n- Respect des 183 Jours : Nos outils de tracking vous aident à prouver que vous passez moins de 6 mois en France, validant votre statut international.\n- Liberté Sécurisée : Voyagez sereinement en sachant que votre structure fiscale est carrée, documentée et reconnue par les conventions OCDE.", ctaText: "Valider ma Règle des 183 Jours" },
  { slug: "freelance-ia-midjourney-stable-diffusion-ltd-uk", title: "Freelance IA : Facturer via LTD UK 2026", category: "Performance", excerpt: "Monétiser vos prompts sans URSSAF. Le cadre Technology Company.", targetTool: 'calculator', targetAnchor: 'simulator', relatedSlugs: ["freelance-it-ltd-uk-vs-portage-ir35"], keywords: ["IA", "Prompt"], content: "Les métiers de l'IA (Prompt Engineer, AI Artist, Automation Specialist) explosent, mais l'administration française ne sait pas comment les classer.\n\n## La Frustration : L'incertitude administrative du 'nouveau monde'\n\nEn France, vous hésitez entre BNC, Artisan ou Profession Libérale, avec des taux de cotisations qui varient du simple au double. L'IA nécessite des investissements lourds en GPU et abonnements SaaS qui sont difficilement déductibles en micro-entreprise.\n\n> baromètre\n> Le marché européen de l'IA générative pro devrait croître de +42% par an jusqu'en 2026. Ne laissez pas la bureaucratie freiner votre scalabilité.\n\n## La Solution : Le Véhicule Agile 'UK Tech'\n\nLa Limited UK offre un cadre 'Technology Company' générique parfait pour ces nouvelles activités sans case administrative restrictive.\n\n- Déductibilité Immédiate : Vos abonnements (Midjourney, ChatGPT Team, Claude API) et votre matériel GPU cloud sont des charges déductibles à 100%.\n- Facturation Mondiale : Facturez vos clients (souvent US ou Asie) sans TVA et encaissez en $ sans frais de change via votre banque UK.\n- Vitesse d'Exécution : Créez votre structure en 24h et émettez votre première facture dès lundi pour capter les opportunités du marché IA.", ctaText: "Simuler mes gains IA" },

  // --- PREMIERS PAS DÉBUTANTS ---
  { slug: "premier-ltd-uk-francais-guide-zero-experience", title: "Ma 1ère LTD UK : Guide Zéro Expérience 2026", category: "Stratégie", excerpt: "Créer sa boîte anglaise sans jargon. Simple. Digital. 24h.", targetTool: 'bureaucracy', targetAnchor: 'obs/bureaucracy', relatedSlugs: ["micro-entrepreneur-passage-ltd-uk-guide"], keywords: ["Débutant", "Guide"], content: "Vous n'avez jamais créé de société et l'anglais comptable vous terrifie ? En 2026, la barrière à l'entrée est tombée.\n\n## La Frustration : L'enfer du Kbis et du Notaire\n\nEn France, créer une SAS ou une SARL nécessite des semaines d'attente, des rendez-vous physiques chez le greffe, un capital social bloqué et des centaines d'euros de frais de publication légale. C'est un frein à l'énergie créatrice.\n\n> baromètre\n> Le Royaume-Uni reste la juridiction la plus rapide d'Europe avec un délai moyen de création de 4 heures et 22 minutes via le système 'Web Incorporation' en 2025.\n\n## La Solution : Le Modèle 'Cloud Company'\n\nLa Limited (LTD) est la forme juridique la plus légère et la plus moderne au monde.\n\n- 100% Digital : Pas de notaire, pas de voyage à Londres. Tout se signe sur votre smartphone.\n- Capital Flexible : Pas besoin de bloquer des milliers d'euros ; 1£ suffit pour démarrer légalement.\n- Accompagnement BritFlow : Nous traduisons la complexité en simplicité pour que vous puissiez facturer dès demain sans être un expert en Common Law.", ctaText: "Créer ma Structure UK en 24h" },
  { slug: "erreurs-creation-ltd-uk-resident-france-pieges", title: "Top 5 Erreurs : Créer une LTD depuis la France", category: "Urgence", excerpt: "Ce qui peut vous coûter cher. Évitez la liste noire fiscale 2026.", targetTool: 'director-shield', targetAnchor: 'panic-vault', relatedSlugs: ["etablissement-stable-requalification"], keywords: ["Erreur", "Danger"], content: "Créer une structure à Londres est simple, mais la gérer depuis la France sans précautions est une bombe à retardement.\n\n## La Frustration : La 'découverte' tardive du fisc\n\nBeaucoup d'entrepreneurs pensent être invisibles grâce au UK. C'est faux. L'erreur de conformité ne pardonne pas et peut transformer une stratégie d'optimisation en redressement pour fraude fiscale internationale.\n\n> baromètre\n> 80% des failles de conformité détectées en 2025 concernent des omissions de déclaration de comptes étrangers (formulaire 3916) par méconnaissance des règles.\n\n## La Solution : Le Top 5 du Dirigeant Averti\n\n- 1. Registered Office : Ne jamais utiliser votre adresse personnelle française au registre UK (illégal et visible par tous).\n- 2. Reporting CRS : Déclarez systématiquement l'existence de votre LTD au fisc français pour éviter l'amende de 1 500€ par compte.\n- 3. Mind and Management : Ne signez pas vos contrats stratégiques depuis votre salon à Paris sans validation de substance UK.\n- 4. Dividendes sans Profit : Ne confondez pas CA et bénéfice distribuable (illegal dividend).\n- 5. Confirmation Statement : Ne ratez pas l'échéance annuelle du Companies House sous peine de dissolution forcée de votre 'tank'.", ctaText: "Éviter les 5 Erreurs Fatales" },

  // --- VC & SCALE-UP ---
  { slug: "pitch-deck-ltd-uk-levee-fonds-seed", title: "Pitch Deck : Pourquoi le Seed aime le UK en 2026", category: "Expansion", excerpt: "Convaincre les VCs avec une Delaware européenne. La TopCo londonienne.", targetTool: 'expansion', targetAnchor: 'expansion-hub', relatedSlugs: ["levee-de-fonds-vc-advantages-uk"], keywords: ["VC", "Startup"], content: "Les investisseurs internationaux détestent la complexité. Une SAS française avec son pacte d'associés rigide fait peur aux Business Angels US et asiatiques.\n\n## La Frustration : Le 'Légal Check' qui tue le deal\n\nBeaucoup de levées de fonds échouent ou prennent 6 mois à cause d'un audit juridique trop lourd sur les structures continentales. La rigidité du code du commerce français freine l'émission de bons de souscription (BSPCE) ou de notes convertibles.\n\n> OBSERVATOIRE\n> En 2025, plus de 60% des startups de la French Tech levant plus de 5M€ ont créé une holding au Royaume-Uni ou au Delaware pour faciliter le deal flow.\n\n## La Solution : La 'Delaware' de l'Europe\n\nPrésenter un Pitch Deck avec une structure UK (TopCo) montre que vous êtes prêt pour le scale global.\n\n- Standardisation : La Limited est le standard mondial, compréhensible par n'importe quel fonds d'investissement.\n- Flexibilité Equity : Émettez des options (EMI) ou de nouvelles classes d'actions en quelques clics sans assemblée générale extraordinaire coûteuse.\n- Friendly Exits : Le droit des sociétés UK est conçu pour la sortie, facilitant les rachats par des géants de la Tech mondiale.", ctaText: "Convaincre les VCs UK" },
  { slug: "sepa-instant-ltd-uk-banque-virement", title: "SEPA Instant : LTD UK & Virements en 10s", category: "Banque", excerpt: "encaisser l'Europe sans délais. L'IBAN GB au service du cash-flow.", targetTool: 'banking', targetAnchor: 'banking-shield', relatedSlugs: ["compte-bancaire-ltd-uk-resident-francais-wise"], keywords: ["SEPA", "Virement"], content: "Une crainte fréquente : 'Une banque UK accepte-t-elle les virements européens post-Brexit ?'. La réponse est technologique.\n\n## La Frustration : Les délais SWIFT du siècle dernier\n\nAttendre 3 à 5 jours qu'un client vous paie parce que l'argent doit traverser des réseaux de correspondants bancaires est inacceptable en 2026. Ce délai paralyse votre trésorerie et vos investissements publicitaires.\n\n> OBSERVATOIRE\n> Depuis le 1er janvier 2025, la législation européenne impose aux banques le SEPA Instant obligatoire. Les banques UK, via le réseau TIPS, sont déjà nativement compatibles.\n\n## La Solution : La Fluidité Multi-Rail\n\nAvec des comptes comme Wise, Revolut Business ou Starling, votre LTD UK dispose d'un IBAN 'GB' mais aussi souvent d'un IBAN local européen.\n\n- Encaissement en 10 secondes : Recevez vos fonds instantanément, 24h/24 et 7j/7.\n- Zéro Frais de Change SEPA : Encaissez en Euros sur votre sous-compte EUR et convertissez seulement quand vous le décidez.\n- Native FPS : Bénéficiez également du Faster Payments System britannique pour vos paiements internes au UK en moins de 2 minutes.", ctaText: "Encaisser l'Europe en 10 Secondes" },

  { slug: "velocity-scaling-solopreneur-agence", title: "Velocity Scaling : De Solo à Agence via Londres", category: "Expansion", excerpt: "Scaler son business sans l'effet de seuil social français. Le moteur de croissance.", targetTool: 'expansion', targetAnchor: 'expansion-hub', relatedSlugs: ["recrutement-global-talent-international"], keywords: ["Scale", "Growth"], content: "Passer de freelance solopreneur à patron d'agence est un saut périlleux en France à cause de la progression brutale des charges sociales.\n\n## La Frustration : L'inertie sociale qui tue la croissance\n\nRecruter votre premier collaborateur en France double vos charges administratives et fait exploser votre point mort. Vous passez d'une agilité totale à un carcan de délais de préavis et de menaces prud'homales qui freinent votre ambition.\n\n> OBSERVATOIRE\n> 1 startup sur 2 en phase de scale choisit de recruter ses consultants internationaux via une structure UK pour bénéficier de la souplesse du contrat de 'Consultancy'.\n\n## La Solution : La Culture du Service Londonienne\n\nLondres est l'accélérateur idéal pour ce virage. La culture business britannique est tournée vers la croissance et la simplicité contractuelle.\n\n- Contrats Agiles : Recrutez des talents mondiaux sans les lourdeurs du CDI français.\n- Levée de fonds Seed : Accédez au hub n°1 de financement européen pour financer votre déploiement marketing.\n- Visibilité Internationale : Transformez votre expertise individuelle en une marque globale reconnue par de grands comptes US ou Européens.", ctaText: "Lancer mon Velocity Scaling" },
  { slug: "levee-de-fonds-vc-advantages-uk", title: "Levée de fonds : Pourquoi les VCs adorent le UK en 2026", category: "Expansion", excerpt: "La flexibilité de la Common Law pour investir sereinement.", targetTool: 'expansion', targetAnchor: 'expansion-hub', relatedSlugs: ["velocity-scaling-solopreneur-agence"], keywords: ["VC", "Seed"], content: "Si vous ambitionnez de lever des fonds auprès de VCs internationaux, une structure française peut être un 'red flag' bureaucratique.\n\n## La Frustration : La rigidité des pactes d'associés français\n\nLa complexité du droit des sociétés français et l'intervention systématique de notaires pour le moindre mouvement de capital effrayent les investisseurs anglo-saxons. Le manque de flexibilité sur les paliers de 'Vesting' rallonge les transactions de plusieurs mois.\n\n> OBSERVATOIRE\n> Le Royaume-Uni a capté 38% de l'investissement total en capital-risque en Europe en 2024, soit deux fois plus que la France.\n\n## La Solution : Le Standard Mondial Common Law\n\nUne Limited UK est le véhicule préféré des VCs car elle utilise des standards documentaires (BVCA) reconnus mondialement.\n\n- Mécanismes de Vesting : Protégez les fondateurs et investisseurs avec des règles claires et automatisables.\n- Actions Préférentielles : Gérez les droits de vote et de liquidation avec une précision chirurgicale.\n- Prêt pour l'Exit : Une structure UK est conçue pour être vendable instantanément à un groupe coté au NASDAQ ou au LSE.", ctaText: "Préparer ma Levée de Fonds" },

  { slug: "recrutement-global-talent-international", title: "Hiring : Recruter des consultants sans risque en 2026", category: "Expansion", excerpt: "Éviter le salariat déguisé via le UK. L'agilité consultant vs consultant.", targetTool: 'expansion', targetAnchor: 'expansion-hub', relatedSlugs: ["velocity-scaling-solopreneur-agence"], keywords: ["Remote", "Talent"], content: "Recruter en France via des contrats de prestation comporte un risque majeur de requalification en CDI ('salariat déguisé').\n\n## La Frustration : La bombe à retardement URSSAF\n\nSi vous travaillez avec des freelances réguliers en France, l'URSSAF peut considérer qu'il existe un lien de subordination. Vous risquez des redressements massifs sur les cotisations passées et la titularisation forcée du prestataire. Votre agilité devient votre faiblesse.\n\n> baromètre\n> Les contrôles sur le 'faux travail indépendant' ont augmenté de 28% en France en 2025, ciblant spécifiquement les startups du numérique.\n\n## La Solution : Le cadre IR35 UK (Consultancy Agreement)\n\nEn gérant votre équipe de talents mondiaux via votre Limited UK, vous utilisez des standards internationaux bien plus cadrés.\n\n- Prestation B2B Réelle : Le droit anglais définit strictement l'indépendance via la clause de substitution et l'absence de contrôle managérial direct.\n- Accès au Pool Mondial : Écartez les frontières du recrutement ; signez des experts de n'importe quel pays avec un contrat de droit anglais reconnu partout.\n- Arbitrage de Risque : Isolez votre centre de profit au UK pour éviter les dérives jurisprudentielles du droit du travail français.", ctaText: "Recruter à l'International" },
  { slug: "nomadisme-digital-residence-fiscale-audit", title: "Nomadisme : Quitter la France fiscalement en 2026", category: "Stratégie", excerpt: "Audit de résidence pour nomades digitaux. Sortir du radar de Bercy.", targetTool: 'nomad', targetAnchor: 'nomad-scanner', relatedSlugs: ["expatriation-dubai-via-londres"], keywords: ["Nomad", "Expat"], content: "Le nomadisme digital n'est plus une zone d'ombre. Les administrations fiscales sont passées à l'ère du Big Data.\n\n## La Frustration : La présomption de résidence française\n\nSi vous voyagez sans port d'attache clair, Bercy peut revendiquer votre résidence fiscale dès lors que vous gardez une carte bancaire, une famille ou des clients en France. Vous risquez un redressement sur l'intégralité de vos revenus mondiaux des 3 dernières années.\n\n> baromètre\n> Le croisement des données de géo-localisation et des flux bancaires internationaux permet désormais au fisc de détecter les 'faux expatriés' en moins de 12 mois.\n\n## La Solution : Le Hub de Résidence Administrative UK\n\nÉtablissez votre centre d'intérêts économiques au UK via une Limited et une adresse de correspondance réelle.\n\n- Preuve de Substance : Justifiez que votre business est piloté depuis Londres, créant une barrière de protection contre l'article 4B du CGI français.\n- Respect des 183 Jours : Nos outils de tracking vous aident à prouver que vous passez moins de 6 mois en France, validant votre statut international.\n- Liberté Sécurisée : Voyagez sereinement en sachant que votre structure fiscale est carrée, documentée et reconnue par les conventions OCDE.", ctaText: "Scanner ma Résidence Nomade" },
  { slug: "expatriation-dubai-via-londres", title: "Dubaï + Londres : Le Combo Gagnant 2026", category: "Stratégie", excerpt: "Opérer au UK, résider à Dubaï. Le montage de l'hyper-croissance.", targetTool: 'nomad', targetAnchor: 'nomad-scanner', relatedSlugs: ["nomadisme-digital-residence-fiscale-audit"], keywords: ["Dubaï", "0%"], content: "Pour l'entrepreneur à succès, le choix de la juridiction est un levier de multiplicateur de capital.\n\n## La Frustration : L'opacité bancaire de Dubaï\n\nAvoir une société à Dubaï est fantastique pour le 0% d'impôt, mais c'est un calvaire pour facturer des clients européens ou US. Beaucoup de banques occidentales refusent les virements de structures 'Freezone', vous obligeant à des justifications interminables pour chaque euro encaissé.\n\n> baromètre\n> Depuis l'introduction de l'IS à 9% à Dubaï en 2024, l'intérêt pour les sociétés hybrides UK-Dubaï a triplé pour conserver la flexibilité internationale.\n\n## La Solution : Prestige Londonien + Cash-flow Dubaï\n\nLe montage hybride permet d'avoir le meilleur des deux mondes : une Limited UK pour la face client, et une résidence à Dubaï pour l'encaissement personnel.\n\n- Facturation Premium : Vos clients receivez une facture d'une société de la City, gage de confiance absolue.\n- Bancarisation Fluide : Gérez votre cash au UK via des institutions de premier rang (HSBC, Barclays, Revolut pro).\n- Dividendes à 0% : Remontez vos profits britanniques (après 19% d'IS) vers votre résidence de Dubaï pour un net personnel imbattable mondialement.", ctaText: "Scanner mon Expatriation" },
  { slug: "rd-tax-credit-innovation-londres", title: "R&D Tax Credit : Booster son innovation au UK", category: "Expansion", excerpt: "Le CIR britannique à 27% de cash direct. Plus simple que la France.", targetTool: 'expansion', targetAnchor: 'expansion-hub', relatedSlugs: ["levee-de-fonds-vc-advantages-uk"], keywords: ["R&D", "Innovation"], content: "Financer la tech est un combat quotidien. Le Royaume-Uni a fait le choix de l'efficacité administrative.\n\n## La Frustration : Le CIR français comme 'fusil à un coup'\n\nEn France, le Crédit Impôt Recherche est puissant mais complexe. Le délai de remboursement peut prendre des mois, et les contrôles fiscaux a posteriori sont la norme, créant une épée de Damoclès sur votre trésorerie.\n\n> baromètre\n> Le nouveau régime 'R&D intensive SME' au UK pour 2025-2026 permet un remboursement cash allant jusqu'à £27 pour £100 dépensées en innovation.\n\n## La Solution : Levier de Liquidité Immédiat\n\nLondres récompense l'audace technique avec un système basé sur la confiance et la rapidité.\n\n- Remboursement Rapide : Récupérez du cash sonnant et trébuchant même si votre société ne paie pas encore d'IS.\n- Définition Large : L'innovation logicielle, l'IA et les process propriétaires rentrent largement dans les critères d'éligibilité.\n- Zéro Dilution : Financez votre R&D avec l'argent du fisc au lieu de sacrifier vos parts sociales trop tôt auprès de VCs.", ctaText: "Simuler ma Croissance Tech" },
  { slug: "immobilier-uk-buy-to-let-holding", title: "Immobilier UK : Investir via sa Limited", category: "Patrimoine", excerpt: "Capitaliser ses profits Ltd dans la brique UK.", targetTool: 'wealth', targetAnchor: 'wealth-audit', relatedSlugs: ["protection-sci-urssaf-holding-uk"], keywords: ["Brique", "Rent"], content: "Investir ses dividendes UK dans l'immobilier britannique est le cycle vertueux par excellence.\n\n## La Frustration : L'immobilier français, un gouffre fiscal\n\nEn France, les revenus fonciers sont lourdement taxés (jusqu'à 45% d'IR + 17.2% de prélèvements sociaux). Les intérêts d'emprunt ne sont plus entièrement déductibles et la fiscalité sur les plus-values est confiscatoire. Votre patrimoine s'érode au lieu de fructifier.\n\n> baromètre\n> En 2026, un investisseur immobilier français perd en moyenne 18% de rendement net par rapport à son homologue britannique, uniquement à cause de la fiscalité.\n\n## La Solution : Le Buy-to-Let via Limited UK\n\nLe Royaume-Uni offre un cadre fiscal et juridique idéal pour l'investissement locatif.\n\n- Fiscalité Optimisée : Les intérêts d'emprunt sont déductibles de votre profit pro. Vous ne payez l'impôt sur les sociétés (19%) que sur le résultat net.\n- Rente en Livres Sterling : Constituez-vous une rente dans une devise forte et stable, décorrélée des risques politiques de la zone Euro.\n- Protection du Patrimoine : Votre Limited UK est un coffre-fort juridique qui protège vos actifs immobiliers des aléas personnels ou professionnels.", ctaText: "Investir mes Dividendes en Brique" },
  { slug: "compliance-tracfin-kyc-uk", title: "Compliance : Rester clean sur Tracfin", category: "Banque", excerpt: "La discrétion n'est pas l'opacité.", targetTool: 'banking', targetAnchor: 'banking-shield', relatedSlugs: ["banque-uk-vs-offshore-resilience"], keywords: ["KYC", "Tracfin"], content: "Dans un monde de transparence globale, la discrétion est un luxe qui se prépare avec soin.\n\n## La Frustration : Le soupçon permanent des banques françaises\n\nLes banques françaises, sous la pression de Tracfin et des régulateurs, adoptent une posture de suspicion généralisée. Chaque virement international, chaque flux inhabituel déclenche des demandes de KYC interminables, des blocages de compte et des signalements abusifs. Votre temps est précieux, mais vous le passez à justifier l'origine de vos fonds.\n\n> baromètre\n> En 2025, 45% des entrepreneurs français ayant des flux internationaux ont subi au moins un blocage de compte ou une demande de KYC abusive, entraînant des retards de paiement et des pertes de contrats.\n\n## La Solution : La Conformité proactive à la Londonienne\n\nNous vous aidons à naviguer dans les eaux troubles de la compliance internationale en bâtissant un dossier de conformité irréprochable.\n\n- Dossier Robuste : Nous documentons la substance de votre Limited et la légalité de vos flux financiers pour que vous restiez 'clean' face aux régulateurs comme Tracfin.\n- Transparence Maîtrisée : La discrétion n'est pas l'opacité. Nous vous aidons à présenter une image de conformité sans sacrifier votre vie privée.\n- Tranquillité d'Esprit : Assurez-vous que votre ingénierie fiscale est bâtie sur des fondations de conformité inébranlables, vous permettant de vous concentrer sur votre business.", ctaText: "Auditer ma Sécurité Bancaire" },
  { slug: "emi-options-attirer-talents-mondiaux", title: "EMI Options : Motiver ses employés au UK", category: "Expansion", excerpt: "Le plan de stock-options ultra-avantageux.", targetTool: 'expansion', targetAnchor: 'expansion-hub', relatedSlugs: ["recrutement-global-talent-international"], keywords: ["Stock", "Bonus"], content: "Attirer les meilleurs talents est la clé de la croissance, mais les schémas d'intéressement français sont rigides et peu incitatifs.\n\n## La Frustration : Des stock-options taxées comme des salaires\n\nEn France, les BSPCE sont complexes, soumis à des conditions strictes et souvent taxés lourdement à la revente. Les plans d'intéressement classiques sont perçus comme des salaires déguisés, avec des charges sociales et fiscales dissuasives. Vous ne pouvez pas rivaliser avec les offres des startups internationales.\n\n> baromètre\n> En 2025, 70% des talents Tech français préfèrent rejoindre une startup avec un plan de stock-options UK ou US, jugé plus avantageux et transparent.\n\n## La Solution : Le programme EMI (Enterprise Management Incentives) UK\n\nLe Royaume-Uni offre l'un des schémas de stock-options les plus généreux au monde, conçu pour les PME et les startups.\n\n- Fiscalité Avantageuse : Fiscalité quasi nulle à l'octroi et imposition très réduite (10% de Capital Gains Tax) sur la plus-value lors de la revente.\n- Flexibilité : Accorder des options d'achat d'actions à vos employés clés est simple et rapide, sans les lourdeurs administratives françaises.\n- Alignement des Intérêts : C'est l'outil indispensable pour aligner les intérêts de votre équipe sur vos objectifs de croissance et fidéliser les talents qui feront le succès de votre agence ou de votre startup à Londres.", ctaText: "Simuler ma Croissance Globale" },

  { slug: "exit-tax-france-eviter-le-piege", title: "Exit Tax : Préparer son départ de France", category: "Stratégie", excerpt: "Protéger sa plus-value latente.", targetTool: 'nomad', targetAnchor: 'nomad-scanner', relatedSlugs: ["nomadisme-digital-residence-fiscale-audit"], keywords: ["Exit", "Départ"], content: "L'Exit Tax est le 'mur de Berlin' fiscal français, une barrière psychologique et financière massive pour tout entrepreneur qui a créé de la valeur.\n\n## La Frustration : Votre plus-value latente 'confisquée' au départ\n\nSi votre entreprise a pris de la valeur, la quitter ou transférer votre résidence fiscale peut déclencher l'Exit Tax française sur vos plus-values latentes. Bercy peut exiger un paiement ou une caution de 30% de la valeur de votre société. C'est un boulet financier qui paralyse votre mobilité internationale et vous empêche de réaliser le fruit de votre travail.\n\n> En 2025, le nombre d'entrepreneurs français assujettis à l'Exit Tax a augmenté de 15%, avec un montant moyen de caution exigée de 250 000€.\n\n## La Solution : Anticiper avec une Holding UK\n\nAnticiper ce départ en structurant vos titres au sein d'une holding britannique avant que la valorisation n'explose est une stratégie de prévoyance élémentaire.\n\n- Gel de la Valorisation : Fixez le point de départ de votre taxe sur une base maîtrisée, bien avant votre départ effectif.\n- Cadre de Sortie Souple : Le Royaume-Uni offre un cadre de sortie bien plus souple et des abattements pour cession de titres (Business Asset Disposal Relief) qui protègent le fruit de vos années de labeur.\n- Liberté Retrouvée : Ne vous laissez pas enfermer dans une prison fiscale : préparez votre porte de sortie internationale en amont de votre succès.", ctaText: "Scanner mon Expatriation" },
  { slug: "facturer-asie-via-londres-hub", title: "Asie : Londres comme hub pour la Chine/HK", category: "Expansion", excerpt: "Le pont financier entre l'Europe et l'Asie.", targetTool: 'expansion', targetAnchor: 'expansion-hub', relatedSlugs: ["facturation-usa-w8ben-convention-uk"], keywords: ["Asie", "HongKong"], content: "Le commerce avec la Chine ou l'Asie du Sud-Est est un marché colossal, mais la logistique bancaire peut être un frein majeur.\n\n## La Frustration : Les banques françaises déconnectées de l'Asie\n\nLes banques françaises peinent à gérer les flux complexes avec l'Asie. Les délais de virement sont longs, les frais de change élevés, et les exigences de conformité spécifiques à chaque pays asiatique sont un casse-tête. Vous perdez du temps et de l'argent à chaque transaction.\n\n> En 2025, les entreprises françaises commerçant avec l'Asie perdent en moyenne 3% de leur marge en frais bancaires et délais de paiement, soit 30 000€ sur 1M€ de CA.\n\n## La Solution : Le Pont Financier Londonien\n\nLondres, en raison de son histoire et de sa position géographique, est le pont naturel entre l'Europe et les marchés asiatiques.\n\n- Corridors Directs : Les banques londoniennes disposent de corridors directs pour les règlements en Renminbi (RMB) ou en Dollar de Hong Kong (HKD), garantissant rapidité et efficacité.\n- Fluidité Opérationnelle : Utiliser votre Limited UK pour centraliser vos transactions asiatiques vous offre une réduction des coûts de change et une crédibilité institutionnelle.\n- Crédibilité Internationale : Une structure UK est reconnue et respectée par les partenaires asiatiques, facilitant les négociations et les partenariats. Capitalisez sur la puissance de la City pour conquérir l'Est.", ctaText: "Lancer mon Expansion Asie" },
  { slug: "holding-animee-vs-passive-audit", title: "Holding Animée : Valider la substance", category: "Fiscalité", excerpt: "Éviter la qualification de holding passive.", targetTool: 'substance', targetAnchor: 'substance-audit', relatedSlugs: ["audit-substance-defense-controle-fiscal"], keywords: ["Holding", "Audit"], content: "Pour bénéficier des exonérations fiscales comme le régime 'Mère-Fille', une holding ne doit pas être une simple boîte aux lettres. Bercy cherche à requalifier les structures en 'holdings passives' pour refuser la déductibilité des charges et taxer les dividendes au taux plein. La 'Holding Animée' britannique doit participer activement à la politique du groupe, fournir des services réels à ses filiales (IT, finance, RH) et disposer d'une gouvernance locale incontestable. Nous auditons vos statuts, vos contrats inter-compagnies et vos procès-verbaux de Board pour garantir que votre holding londonienne est l'organe moteur de votre groupe, inattaquable devant n'importe quelle juridiction fiscale.", ctaText: "Lancer mon Audit de Substance" },
  { slug: "secret-professionnel-discretion-uk", title: "Discrétion : Le secret professionnel UK", category: "Protection", excerpt: "Gérer sa visibilité face aux tiers curieux.", targetTool: 'director-shield', targetAnchor: 'director-protection?mode=divorce', relatedSlugs: ["divorce-protection-parts-societe-uk"], keywords: ["Secret", "Privé"], content: "En France, n'importe qui peut consulter le nom des actionnaires et le bilan d'une société sur les registres publics. Cette transparence forcée peut être un danger lors d'un divorce, d'un litige professionnel ou simplement pour votre discrétion personnelle. Le Royaume-Uni offre des services de 'Nominee' et de 'Registered Office' qui permettent de dissocier votre adresse personnelle et votre identité publique de votre structure commerciale. De plus, le droit anglais protège farouchement le secret des affaires et les échanges entre l'entreprise et ses conseillers juridiques. Pilotez vos affaires avec une visibilité choisie, pas subie, et protégez-vous de la curiosité malveillante des tiers.", ctaText: "Protéger ma Discrétion" },
  { slug: "optimisation-tva-services-digitaux", title: "TVA Services : Optimiser ses ventes B2B", category: "Performance", excerpt: "Règles d'auto-liquidation et seuils UK.", targetTool: 'calculator', targetAnchor: 'simulator?mode=tva', relatedSlugs: ["ecommerce-tva-brexit-londres"], keywords: ["TVA", "B2B"], content: "Vendre des services digitaux (SaaS, formation, coaching) à l'international impose une gestion rigoureuse des règles de territorialité de la TVA. Au Royaume-Uni, si vous vendez à des entreprises étrangères (B2B), le mécanisme d'auto-liquidation s'applique souvent, supprimant la friction de la TVA sur vos factures sortantes. De plus, le seuil de £90,000 pour l'inscription obligatoire à la TVA au UK permet aux agences de niche de démarrer avec une marge compétitive imbattable. Ne laissez pas la complexité de la TVA UE freiner votre croissance mondiale : utilisez le cadre UK pour facturer vos clients sans les contraintes administratives obsolètes du continent.", ctaText: "Scanner ma Fiscalité" },
  { slug: "privacy-directors-address-shield-service", title: "Privacy : Cacher son adresse personnelle au registre", category: "Protection", excerpt: "Le Service Address au UK. Protéger votre vie privée 2026.", targetTool: 'privacy', targetAnchor: 'panic-vault', relatedSlugs: ["interdiction-gerer-france-solution-londres"], keywords: ["Privacy", "Adresse"], content: "En France, votre adresse personnelle est souvent publique sur votre Kbis si vous travaillez de chez vous. C'est un risque de sécurité majeur.\n\n## La Frustration : Votre foyer exposé aux yeux de tous\n\nN'importe quel client mécontent, créancier ou curieux peut trouver votre domicile en trois clics sur societe.com. Pour un entrepreneur opérant dans des secteurs sensibles ou simplement protecteur de sa famille, cette transparence forcée est un danger.\n\n> Le Royaume-Uni a renforcé en 2025 la protection des données des dirigeants via le 'Directors' Residential Address Shield'.\n\n## La Solution : Le Blindage du Registre UK\n\nGrâce au service de 'Service Address' britannique, votre adresse personnelle n'apparaît JAMAIS publiquement.\n\n- Adresse de Prestige : Affichez une adresse de prestige dans la City de Londres sur tout le registre public.\n- Secret Bancaire Applicatif : Seuls les régulateurs connaissent votre foyer ; le public et vos concurrents ne voient que votre siège social.\n- Sérénité Totale : Séparez physiquement et juridiquement votre vie de famille de vos responsabilités de Director.", ctaText: "Activer mon Bouclier Privacy" },
  { slug: "strategie-tresorerie-long-terme-capitalisation", title: "Capitalisation : Bâtir un empire sur 10 ans", category: "Patrimoine", excerpt: "Utiliser le UK comme coffre-fort fiscal.", targetTool: 'wealth', targetAnchor: 'wealth-audit', relatedSlugs: ["succession-heritage-holding-londres"], keywords: ["Empire", "Trésor"], content: "La richesse ne se construit pas en un an, mais sur une décennie de décisions intelligentes.\n\n## La Frustration : L'érosion de votre capital par l'inflation et la fiscalité\n\nEn France, l'inflation ronge votre épargne et la fiscalité confiscatoire (IS, Flat Tax, droits de succession) limite drastiquement votre capacité à capitaliser. Chaque euro gagné est ponctionné, réduisant l'effet des intérêts composés. Votre trésorerie est une cible facile pour les créanciers et l'administration.\n\n> Sur 10 ans, un capital de 1M€ géré en France perd en moyenne 35% de sa valeur réelle par rapport à une gestion optimisée via une Limited UK, à cause de l'inflation et de la fiscalité.\n\n## La Solution : Le UK, votre Family Office personnel\n\nUtiliser une Limited UK comme véhicule de capitalisation à long terme est le meilleur moyen de protéger votre pouvoir d'achat et de bâtir un empire financier.\n\n- Effet de Levier Fiscal : Laissez vos profits travailler au sein d'une structure taxée à 19%, bénéficiant de l'effet des intérêts composés sur une base de capital plus large.\n- Protection Robuste : Votre Limited devient votre 'coffre-fort' personnel, capable d'investir globalement dans l'immobilier, les actions ou les cryptos, tout en restant un bouclier contre les saisies.\n- Liberté d'Investissement : Gérez votre patrimoine avec la flexibilité d'un Family Office, sans les contraintes administratives et fiscales françaises. Voyez loin, voyez grand, et utilisez Londres comme le hub central de votre empire financier.", ctaText: "Bâtir mon Empire sur 10 Ans" },

  // --- NOUVEAUX OUTILS INTÉRACTIFS (Février 2025) ---

  // --- FISCAL EXODUS PROJECT (Data Journalism Link Baiting) ---
  { slug: "prudhommes-bouclier-tresorerie-uk", title: "Prud'hommes : Sanctuariser sa Trésorerie au UK", category: "Protection", excerpt: "Éviter la saisie immédiate de votre cash par l'exécution provisoire.", targetTool: 'director-shield', targetAnchor: 'director-protection?mode=blackmail', relatedSlugs: ["prudhommes-isoler-cash-execution-forcee"], keywords: ["Prudhommes", "Saisie", "Cash"], content: "Un litige social en France peut vous ruiner avant même que vous n'ayez pu vous défendre.\n\n## La Frustration : L'exécution provisoire, ou la mort subite\n\nLe conseil des Prud'hommes impose souvent l'exécution provisoire de sa condamnation. L'huissier peut alors prélever les fonds sur votre compte bancaire français dès le lendemain du jugement, même si vous faites appel. Pour une PME, c'est l'asphyxie immédiate.\n\n> OBSERVATOIRE\n> En 2025, près de 40% des liquidations de PME de services font suite à une condamnation prud'homale imprévue avec exécution immédiate.\n\n## La Solution : Le Mur de Cash UK\n\nEn logeant votre trésorerie de réserve dans une Limited UK via des remontées de profit documentées, vous désarmez cette menace.\n\n- Insaisissabilité Directe : Pas de saisie administrative ou judiciaire automatique sur un compte britannique FCA.\n- Délai de Négociation : Forcez l'accord en montrant que votre cash est en sécurité et que vous contrôlez le calendrier financier.\n- Sauvetage du Business : Gardez les munitions nécessaires pour financer votre défense et la continuité de votre activité.", ctaText: "Protéger ma Trésorerie" },
  { slug: "succession-dirigeant-holding-uk", title: "Succession : Transmettre sans les 45% de taxes 2026", category: "Patrimoine", excerpt: "Comment protéger vos héritiers de la fiscalité successorale française via FIC.", targetTool: 'wealth', targetAnchor: 'wealth-audit?mode=inheritance', relatedSlugs: ["succession-heritage-holding-londres"], keywords: ["Succession", "Héritage", "Fils"], content: "L'impôt sur le décès est le plus injuste des impôts. Chez BritFlow, nous pensons que votre travail doit revenir à vos enfants, pas à Bercy.\n\n## La Frustration : La vente forcée de l'entreprise familiale\n\nEn France, si vous ne préparez pas votre succession 10 ans à l'avance via des montages complexes, vos héritiers seront taxés à 45%. Pour payer, ils devront souvent brader la société ou s'endetter sur 20 ans.\n\n> OBSERVATOIRE\n> Le rendement des successions en France a bondi de +12% en 2025, illustrant le manque cruel de solutions de transmission agiles pour les dirigeants.\n\n## La Solution : La Structure de Transmission FIC\n\n- Démembrement Transfrontalier : Transmettez la nue-propriété de vos parts de holding UK à vos enfants avec une base fiscale optimisée.\n- Common Law Flexibility : Organisez votre succession avec la souplesse d'un contrat privé, hors du carcan du droit de réserve héréditaire rigide.\n- Pérennité du Capital : Votre empire financier reste intact, piloté depuis Londres, prêt pour la génération suivante.", ctaText: "Sécuriser mon Héritage" },
  { slug: "crypto-banking-exclusion-solution-uk", title: "Banques vs Crypto : La fin de l'exclusion via le UK", category: "Banque", excerpt: "Éviter la fermeture de compte et l'exclusion bancaire liée aux actifs numériques.", targetTool: 'bank-matchmaker', targetAnchor: 'obs/banques', relatedSlugs: ["crypto-actifs-societe-uk-capitalisation"], keywords: ["Crypto", "Banque", "Blocage"], content: "Les banques françaises ont déclaré la guerre aux portefeuilles crypto. Ne soyez pas une victime collatérale.\n\n## La Frustration : Le compte clôturé pour 'virement de plateforme'\n\nEn France, recevoir 10 000€ d'un exchange (Kraken, Binance, Coinbase) est souvent synonyme de fermeture de compte professionnelle sans préavis pour 'risque de conformité'. Votre banque traditionnelle ne veut pas comprendre votre métier.\n\n> OBSERVATOIRE\n> Le Royaume-Uni a finalisé en 2025 son architecture 'Crypto-Friendly Banking', imposant aux banques des critères objectifs de refus plutôt que l'arbitraire.\n\n## La Solution : La Place Financière Crypto Hub\n\n- EMI Spécialisées : Accédez à des institutions (Wise, Tide, Revolut Business) qui acceptent et comprennent les flux de capitaux numériques.\n- Limited Corporate Account : Ouvrez des versions 'Pro' sur les exchanges avec une entité UK respectée et auditable.\n- Sécurité des Flux : Séparez totalement votre activité crypto de votre banque quotidienne française pour une sérénité totale.", ctaText: "Accéder au Bank Matchmaker" },
];

export const TAX_RATES = {
  FRANCE: { IS: 0.25, SOCIAL_CHARGES: 0.45, DIVIDEND_FLAT_TAX: 0.30, ADMIN_COST_PER_HOUR: 150 },
  UK: { CT: 0.19, NI: 0.138, DIVIDEND_ALLOWANCE: 500, ADMIN_COST_PER_HOUR: 150, DIVIDEND_TAX: 0.0875 }
};
